name: pheed-env

channels:
  - conda-forge
  - defaults

dependencies:
  - codecov
  - mock
  - pip
  - python=3.7
  - pytest
  - scrapy
  - pip:
      - apsjournals
      - arxiv
      - fpdf
      - PyPDF2